name: macOS Build

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

concurrency:  
  group: ${{ github.workflow}}-${{ github.head_ref }}  
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14
    permissions:
      actions: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0.1

      - name: Show current version of Xcode
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Show OpenSSL version
        run: pkg-config --cflags libcrypto

      - name: Install Packages
        run: |
          brew install openssl@3
          brew install miniupnpc rapidjson sqlcipher bzip2 zlib botan@2 libxslt libxml2 ffmpeg qt glib pkg-config

      - name: Checkout submodules
        run: |
          env
          git submodule update --init --remote libbitdht/ libretroshare/ retroshare-webui/
          git submodule update --init supportlibs/librnp supportlibs/rapidjson supportlibs/restbed openpgpsdk/

      - name: CI-Build
        run: |
          BREW_PREFIX="$(brew --prefix)"
          RS_TAG="$(git describe --tags --match "v*.*.*" --abbrev=0 2>/dev/null || echo "v0.0.0")"
          RS_TAG="${RS_TAG#v}"
          IFS='.' read -r RS_MAJOR_VERSION RS_MINOR_VERSION RS_MINI_VERSION <<< "${RS_TAG}"
          RS_EXTRA_VERSION=""
          qmake6 . -r "CONFIG+=rs_macos14.0" "CONFIG+=release" "CONFIG+=rs_autologin" "CONFIG+=no_rs_sam3" "CONFIG+=no_rs_sam3_libsam3" "CONFIG+=rs_no_rnplib" \
          RS_MAJOR_VERSION="${RS_MAJOR_VERSION}" \
          RS_MINOR_VERSION="${RS_MINOR_VERSION}" \
          RS_MINI_VERSION="${RS_MINI_VERSION}" \
          RS_EXTRA_VERSION="${RS_EXTRA_VERSION}" \
          INCLUDEPATH+="${BREW_PREFIX}/opt/openssl@3/include" \
          INCLUDEPATH+="${BREW_PREFIX}/opt/rapidjson/include" \
          INCLUDEPATH+="${BREW_PREFIX}/opt/sqlcipher/include" \
          INCLUDEPATH+="${BREW_PREFIX}/opt/miniupnpc/include" \
          INCLUDEPATH+="${BREW_PREFIX}/opt/libxslt/include" \
          INCLUDEPATH+="${BREW_PREFIX}/opt/libxml2/include" \
          QMAKE_LIBDIR+="${BREW_PREFIX}/opt/openssl@3/lib" \
          QMAKE_LIBDIR+="${BREW_PREFIX}/opt/rapidjson/lib" \
          QMAKE_LIBDIR+="${BREW_PREFIX}/opt/sqlcipher/lib" \
          QMAKE_LIBDIR+="${BREW_PREFIX}/opt/miniupnpc/lib" \
          QMAKE_LIBDIR+="${BREW_PREFIX}/opt/libxslt/lib" \
          QMAKE_LIBDIR+="${BREW_PREFIX}/opt/libxml2/lib" \
          CONFIG+=no_retroshare_service \
          CONFIG+=no_retroshare_friendserver
          make -j"$(sysctl -n hw.ncpu)"
